[build]
  command = "npm run build"
  publish = "dist"
  base = "/"

[context.production]
  environment = { NODE_VERSION = "18" }

[dev]
  command = "remix vite:dev"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"