-- Add to existing tables...

ALTER TABLE blog_posts ADD COLUMN visible BOOLEAN DEFAULT 1;
ALTER TABLE blog_posts ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE portfolio ADD COLUMN visible BOOLEAN DEFAULT 1;
ALTER TABLE portfolio ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE services ADD COLUMN visible BOOLEAN DEFAULT 1;
ALTER TABLE services ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP;